// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0unkjcApUN-m0NGBvLVME-XVcVvQXfGk',
    appId: '1:750769988034:web:822d6030af345c12d8b65b',
    messagingSenderId: '750769988034',
    projectId: 'artsathi-894de',
    authDomain: 'artsathi-894de.firebaseapp.com',
    storageBucket: 'artsathi-894de.appspot.com',
    measurementId: 'G-1RWYWEGMRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwINM1JXRuAKYj0XHY1zltblzN-H1X_do',
    appId: '1:750769988034:android:9bf72809525aabf9d8b65b',
    messagingSenderId: '750769988034',
    projectId: 'artsathi-894de',
    storageBucket: 'artsathi-894de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq20FWnmcHxI3fel-WSUn3A0wTJBS2iWQ',
    appId: '1:750769988034:ios:d7a43530fbe7c579d8b65b',
    messagingSenderId: '750769988034',
    projectId: 'artsathi-894de',
    storageBucket: 'artsathi-894de.appspot.com',
    iosBundleId: 'com.example.ecommerceAppFirebase',
  );
}
